@startuml
left to right direction

actor :管理者:
actor メンバー
rectangle {
   管理者 --> (ファイルをアップロードする)
   管理者 --> (ファイルの一覧を取得する)
   管理者 --> (ファイルをダウンロードする)
    (ファイルをダウンロードする) <-- メンバー
    (ファイルの一覧を取得する) <-- メンバー
}
@enduml