@startuml usecase
left to right direction

actor 管理者
actor メンバー
rectangle {
    管理者 --> (ログインする)
    管理者 --> (ファイルの一覧を取得する)
    管理者 --> (ファイルをダウンロードする)
    管理者 --> (ファイルをアップロードする)
    (ログインする) <-- メンバー
    (ファイルをダウンロードする) <-- メンバー
    (ファイルの一覧を取得する) <-- メンバー
}
@enduml